name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest

    env:
      Solution_Name: Equation.sln  # Заменить на имя вашего решения

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    - name: Restore dependencies
      run: dotnet restore $env:Solution_Name

    - name: Build
      run: dotnet build $env:Solution_Name --configuration ${{ matrix.configuration }}

    - name: Create coverage directory
      run: New-Item -ItemType Directory -Force -Path ./coverage

    - name: Execute unit tests
      run: |
        if (Test-Path -Path "Equation/Tests.cs") {
          dotnet test Equation/Equation.csproj --configuration ${{ matrix.configuration }} --collect:"XPlat Code Coverage" /p:CoverletOutputFormat=lcov /p:CoverletOutput=./coverage/coverage.info
        } else {
          Write-Host "Tests.cs file not found"
        }

    - name: List all files and directories
      run: Get-ChildItem -Recurse

    - name: List coverage directory
      run: Get-ChildItem ./coverage

    - name: Display contents of coverage file
      run: |
        if (Test-Path -Path "./coverage/coverage.info") {
          Get-Content ./coverage/coverage.info
        } else {
          Write-Host "coverage/coverage.info file not found"
        }

    - name: Upload coverage to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage/coverage.info

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: BuildOutput
        path: |
          **/bin/${{ matrix.configuration }}/
          !**/obj/**
